/*
 * generated by Xtext 2.10.0
 */
package ru.weawer.ww


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class WwDslRuntimeModule extends AbstractWwDslRuntimeModule {
}
