/*
 * generated by Xtext 2.10.0
 */
package ru.weawer.ww


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class WwDslStandaloneSetup extends WwDslStandaloneSetupGenerated {

	def static void doSetup() {
		new WwDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
